name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:

jobs:
  audit:
    uses: panva/.github/.github/workflows/npm-audit.yml@main

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - lts/hydrogen # 18
          - lts/iron # 20
          - current

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          check-latest: true
      - run: npm clean-install
      - run: npm run ci

  # deploy:
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'panva/node-oidc-provider' }}
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       app:
  #         - radiant-refuge-93411
  #         - powerful-cove-31049
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '2.7'
  #     - run: gem install dpl-heroku -v 1.10.14
  #     - run: dpl --provider=heroku --strategy=api --api-key=${{ secrets.HEROKU_AUTH_TOKEN }} --app=${{ matrix.app }}
